# Generated by Django 5.2.4 on 2025-10-15 05:37

import cloudinary_storage.storage
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('pan_number', models.CharField(max_length=20, unique=True)),
                ('pan_image', models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=profiles.models.upload_to_kyc)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('id_card_image', models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=profiles.models.upload_to_kyc)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_relation', models.CharField(max_length=50)),
                ('nominee_dob', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_images/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
