# Generated by Django 5.2.4 on 2025-09-18 10:03

import cloudinary_storage.storage
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='id_card_image',
            field=models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=profiles.models.upload_to_kyc),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='pan_image',
            field=models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=profiles.models.upload_to_kyc),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_images/'),
        ),
    ]
