# Generated by Django 5.2.4 on 2025-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='nominee_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
