# Generated by Django 5.2.4 on 2025-10-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_kyc_nominee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
