# Generated by Django 5.2.4 on 2025-10-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_kyc_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='account_number',
        ),
        migrations.AddField(
            model_name='kyc',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
