# Generated by Django 5.2.4 on 2025-09-18 10:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccountdetails',
            name='qr_code',
            field=models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='payments/qr/'),
        ),
        migrations.AlterField(
            model_name='useraccountdetails',
            name='qr_code',
            field=models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='user_qr_codes/'),
        ),
    ]
