# Generated by Django 5.2.4 on 2025-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='payment_type',
            field=models.CharField(choices=[('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('PhonePay', 'PhonePay'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='payment_type',
            field=models.CharField(choices=[('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('PhonePay', 'PhonePay'), ('Other', 'Other')], default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccountdetails',
            name='upi_type',
            field=models.CharField(choices=[('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('PhonePay', 'PhonePay'), ('Other', 'Other')], max_length=20),
        ),
    ]
