# Generated by Django 5.2.4 on 2025-10-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverification_alter_customuser_whatsapp_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
