# Generated by Django 5.2.4 on 2025-10-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_email_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Failed', 'Failed'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
