# Generated by Django 5.2.4 on 2025-10-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_parent_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pmf_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('part_1_paid', 'Part 1 Paid'), ('fully_paid', 'Fully Paid')], default='not_paid', max_length=20, verbose_name='PMF Status'),
        ),
    ]
