# Generated by Django 5.2.4 on 2025-10-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payment_status'),
        ('users', '0010_customuser_pmf_status'),
    ]

    operations = [
    ]
