# Generated by Django 5.2.4 on 2025-10-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20251008_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='sponsor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
