# Generated by Django 5.2.4 on 2025-10-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20251008_1026'),
        ('users', '0011_merge_20251008_1603'),
        ('users', '0012_alter_registrationrequest_sponsor_id'),
    ]

    operations = [
    ]
