# Generated by Django 5.2.4 on 2025-10-14 15:58

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccountdetails',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminaccountdetails',
            name='micr_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adminaccountdetails',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminaccountdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminaccountdetails',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adminaccountdetails',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminaccountdetails',
            name='qr_code',
            field=models.FileField(blank=True, help_text='Upload bank QR code (PDF or image)', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='admin_qr_codes/'),
        ),
    ]
