# Generated by Django 5.2.4 on 2025-10-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_adminaccountdetails_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccountdetails',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminaccountdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
