# Generated by Django 5.2.4 on 2025-09-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_user_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_mode', models.CharField(blank=True, default='Razorpay', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='not_paid', max_length=20)),
                ('pay_enabled', models.BooleanField(default=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('received', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.level')),
            ],
            options={
                'ordering': ['level__order'],
            },
        ),
    ]
