# Generated by Django 5.2.4 on 2025-10-15 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pmfpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmf_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='level.level'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='userlevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levelpayment',
            name='user_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='level.userlevel'),
        ),
        migrations.AlterUniqueTogether(
            name='userlevel',
            unique_together={('user', 'level')},
        ),
    ]
