# Generated by Django 5.2.4 on 2025-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
