# Generated by Django 5.2.4 on 2025-09-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelpayment',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('Manual', 'Manual')], default='Razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='levelpayment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
