# Generated by Django 5.2.4 on 2025-09-15 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_userlevel_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlevel',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='razorpay_signature',
        ),
        migrations.CreateModel(
            name='LevelPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='level.userlevel')),
            ],
        ),
    ]
