# Generated by Django 5.2.4 on 2025-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_levelpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
