# Generated by Django 5.2.4 on 2025-09-26 07:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0005_userlevel_requested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelpayment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='payment_proofs/'),
        ),
    ]
