# Generated by Django 5.2.4 on 2025-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0006_alter_levelpayment_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelpayment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Failed', 'Failed'), ('Restricted', 'Payment On Hold - Cap Reached')], default='Pending', max_length=20),
        ),
    ]
