# Generated by Django 5.2.4 on 2025-10-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0007_alter_levelpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='level.level'),
        ),
    ]
