# Generated by Django 5.2.4 on 2025-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0009_pmfpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmfpayment',
            name='payment_proof',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='levelpayment',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='payment_mode',
            field=models.CharField(blank=True, default='Manual', max_length=50),
        ),
    ]
