# Generated by Django 5.2.4 on 2025-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0010_pmfpayment_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmfpayment',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('Manual', 'Manual')], default='Razorpay', max_length=20),
        ),
    ]
