# Generated by Django 5.2.4 on 2025-10-12 05:28

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0011_pmfpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmfpayment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='payment_proofs/'),
        ),
    ]
