# Generated by Django 5.2.4 on 2025-10-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminreport', '0001_initial'),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='level_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='level.levelpayment'),
        ),
    ]
